.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. geranium_qt test_geranium_qt
clean: FORCE
	$(MAKE) -C .. geranium_qt_clean test_geranium_qt_clean
check: FORCE
	$(MAKE) -C .. test_geranium_qt_check
geranium-qt geranium-qt.exe: FORCE
	 $(MAKE) -C .. geranium_qt
apk: FORCE
	$(MAKE) -C .. geranium_qt_apk
